from dataclasses import dataclass

@dataclass(frozen=True)
class Colors:
  WHITE: str = "#fefefe"
  GRAY: str = "#aeaeae"
  BLACK: str = "#131313"
  RED: str = "#ed2c2c"
  LIGHTRED: str = "#EF4444"
  GREEN: str = "#3f8d43"
  LIGHTGREEN: str = "#66BB6A"
  BLUE: str = "#1F6AA5"
  LIGHTBLUE: str = "#3B8ED0"


@dataclass(frozen=True)
class Spacing:
  PADX: int = 12
  PADY: int = 12

@dataclass(frozen=True)
class Fonts:
  APP_TITLE: str = ("Arial", 24, "bold")
  SECTION_TITLE: str = ("Arial", 14, "bold")
  LABEL: str = ("Arial", 13, "bold")

@dataclass(frozen=True)
class HtmlTemplates:
  MSE_STEPS: str = """  
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <style>
        /* PDF Page Setup */
        @page {
          size: A4;
          margin: 0.75in;
        }
        body {
          font-family: "Times New Roman", Times, serif;
          line-height: 1.5;
          color: #333333;
          margin: 0; 
        }
        h1 {
          text-align: center;
          font-size: 18pt;
          margin-bottom: 20pt;
          color: #333333;
        }
        h2 {
          font-size: 16pt;
          margin-top: 20pt;
          border-bottom: 1px solid #333333;
          padding-bottom: 5pt;
          color: #333333;
        }
        p {
          font-size: 14pt;
          margin: 10pt 0;
          color: #333333;
        }
        /* Reduced font size for subscripts */
        sub {
          font-size: 1em;
        }
        /* Increased font size for MSE formula */
        .formula-box {
          margin: 20pt 0;
          padding: 16pt;
          text-align: center;
          font-style: italic;
          font-size: 16pt; /* Increased from standard 12pt */
        }
        
        .formula-box p {
          font-size: 16pt;
        }
        /* Table Styling */
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 10pt;
          color: #333333;
        }
        table, th, td {
          border: 1px solid #333333;
        }
        th, td {
          font-size: 12pt;
          padding-top: 8px;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <h1>Calculating Mean Squared Error</h1>
      <h2>Definitions</h2>
      <p><strong>x<sub>1</sub>...x<sub>n</sub></strong>: Function inputs / independent variables.</p>
      <p><strong>y</strong>: Real value (ground truth).</p>
      <p><strong>h</strong>: Predicted values generated by the model.</p>
      <p><strong>δ</strong>: Error (the difference between real and predicted values).</p>
      <h2>Hypothesis</h2>
      <p>w = $weights</p>
      <p>h = Σ w • x = $function_formula</p>
      <h2>Dataset</h2>
      $dataset_table
      <h2>MSE Formula and result</h2>
      <div class="formula-box">
        <p>MSE = <sup>1</sup>/<sub>n</sub> Σ δ<sup>2</sup> = <strong>$mse_result</strong></p>
      </div>
    </body>
    </html>
    """