from models import CreateMseStepsParams
from utils.create_pdf import create_pdf

TEMPLATE = """  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        /* PDF Page Setup */
        @page {
            size: A4;
            margin: 1in;
        }

        body {
            font-family: "Times New Roman", Times, serif;
            line-height: 1.5;
            color: #333333;
            margin: 0; 
        }

        h1 {
            text-align: center;
            font-size: 24pt;
            margin-bottom: 20pt;
            color: #333333;
        }

        h2 {
            font-size: 18pt;
            margin-top: 20pt;
            border-bottom: 1px solid #333333;
            padding-bottom: 5pt;
            color: #333333;
        }

        p {
            font-size: 12pt;
            margin: 10pt 0;
            color: #333333;
        }

        /* Reduced font size for subscripts */
        sub {
            font-size: 0.7em;
        }

        /* Increased font size for MSE formula */
        .formula-box {
            margin: 20pt 0;
            padding: 16pt;
            text-align: center;
            font-style: italic;
            font-size: 16pt; /* Increased from standard 12pt */
        }
        
        .formula-box p {
            font-size: 16pt;
        }

        /* Table Styling */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10pt;
            color: #333333;
        }

        table, th, td {
            border: 1px solid #333333;
        }

        th, td {
            font-size: 12pt;
            padding-top: 8px;
            text-align: center;
        }
    </style>
</head>
<body>

    <h1>Calculating Mean Squared Error</h1>

    <h2>Definitions</h2>
    <p><strong>x<sub>1</sub>...x<sub>n</sub></strong>: Function inputs / independent variables.</p>
    <p><strong>y</strong>: Real value (ground truth).</p>
    <p><strong>h</strong>: Predicted values generated by the model.</p>
    <p><strong>δ</strong>: Error (the difference between real and predicted values).</p>

    <h2>Hypothesis</h2>
    <p>$weights</p>
    <p>h Σ w • x = $function_formula</p>

    <h2>Dataset</h2>
    $dataset_table

    <h2>MSE Formula and result</h2>
    <div class="formula-box">
        <p>MSE = Σ δ<sup>2</sup> = <strong>$mse_result</strong></p>
    </div>

</body>
</html>
"""

def create_mse_steps(params: CreateMseStepsParams):
  function_formula = create_weights(params.weights)
  dataset_table = create_dataset_table(params)
  contents = TEMPLATE
  contents = contents.replace("$function_formula", function_formula)
  contents = contents.replace("$dataset_table", dataset_table)
  contents = contents.replace("$mse_result", str(params.mse))
  create_pdf(contents)


def create_weights(weights: list[float]):
  result = ""

  if weights[0] == 1: result = "x<sub>0</sub>"
  elif weights[0] == -1: result = f"- x<sub>0</sub>"
  else: result = f"{weights[0]} • x<sub>0</sub>"

  for i in range(1, len(weights)):
    if weights[i] == 1: result = f"+ x<sub>{i}</sub>"
    elif weights[i] == -1: result = f"- x<sub>{i}</sub>"
    else: result = f"+ {weights[i]}•x<sub>{i}</sub>"

  return result

def create_dataset_table(params: CreateMseStepsParams):
  table = "<table>"

  # Generating the header rows
  table += "<thead><tr>"

  for i in range(len(params.dataset[0])): table += f"<th>x{i}</th>"

  table += "<th>y</th>"
  table += "<th>h</th>"
  table += "<th>δ</th>"

  table += "</tr></thead>"

  # Generating body
  table += "<tbody>"
  
  for i in range(len(params.dataset)):
    table += "<tr>"

    for j in range(len(params.dataset[i])): table += f"<td>{params.dataset[i][j]}</td>"
    table += f"<td>{params.real_values[i]}</td>"
    table += f"<td>{params.predicted_values[i]}</td>"
    table += f"<td>{params.errors[i]}</td>"

    table += "</tr>"

  table += "</tbody>"
  table += "</table>"

  return table